version: '2'
services:
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=neurdicom
      - POSTGRES_PASSWORD=neurdicom
      - POSTGRES_DB=neurdicom
    ports:
      - "5432:5432"
  api:
    build: ./ndicom_server
    command: [sh, -c, "python ./app.py --rest_port=8080", "python ./app.py --rest_port=8081"]
    volumes:
      # - ./ndicom_server:/app
      - ./images:/images
    environment:
      - DB_NAME=neurdicom
      - DB_USER=neurdicom
      - DB_PASSWORD=neurdicom
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
  # front:
  #   build: ./ndicom_client
  #   # command: npm start
  #   volumes:
  #     - ./ndicom_client:/app
  #     - node-modules:/app/node_modules
  #   environment:
  #     - API_HOST=api
  #     - API_URL_BROWSER=/api
  #     - API_URL=http://api:3000/
  #     - API_PORT=8080
  #   ports:
  #     - "3000:3000"
  nginx:
    image: nginx
    depends_on:
      - api
      # - front
    ports:
      - "80:80"
    volumes:
      - ./neurdicom.dev.conf:/etc/nginx/conf.d/default.conf
      - ./ndicom_client/build:/mnt/front
    expose:
      - "80"
volumes:
  pg-data:
  # node-modules:
